### ISSUE TITLE
jsmin: Asset-merger don't remove inline comments on production

### ISSUE THREAD

**Issue by Vadorequest** [OpenBuildings/asset-merger#27]
My code works fine in `development` mode, but when I try to run it in `production`:

```js
/* File: application\cache\assets\themes\default/js/fancybox/jquery.fancybox-buttons.js
   Compiled at: 2014-03-30 21:07:18 
================================ */
(function ($){//Shortcut for fancyBox object var F=$.fancybox;//Add helper object F.helpers.buttons={defaults:{skipSingle:false,// disables if gallery contains single image position:'top',...
```

Of course, this doesn't works. Why the inline comments are not deleted before the file is minified? I use `'processor' => 'jsmin'`.

How can I fix this? I don't know if this issue is from jsmin or asset-merger.

**Comment by piotrgolasz** [comment]
I can confirm this issue is still persistent when using double slashes as comments.
However the comments are removed when wrapped inside slash-star comments
This doesn't get striped:
`h1{
	//This is something
	color: red;
}`

This does:
`h1{
	/*This is something*/
	color: red;
}`

Because this is an issue with underlying library, not asset-merger per se, I think I don't have any solutions for you other than use the second type of commenting :/
